name: API Deploy

on:
  workflow_call:
  push:
    branches:
      - develop
    paths:
      - 'packages/api-rails/**'
      - '.github/workflows/api-deploy.yml'

permissions:
  id-token: write
  deployments: write
  statuses: write
  contents: read

jobs:
  migrate:
    name: DB migrate
    runs-on: ubuntu-latest
    environment: api-rails/${{github.ref_name == 'main' && 'prod' || github.ref_name == 'develop' && 'stg'}}

    defaults:
      run:
        working-directory: ./packages/api-rails

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "I am doing a noop deploy"

  api:
    needs: [migrate]
    name: API Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "I am doing a noop deploy"
      - name: Echo Migrate Environment
        run: echo "environment=${{ jobs.migrate.environment }}"
      - name: Echo API Environment
        run: echo "environment=${{ jobs.api.environment }}"

  sidekiq:
    needs: [migrate]
    name: Sidekiq Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "I am doing a noop deploy"

  job:
    needs: [migrate]
    name: Job Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "I am doing a noop deploy"
