name: API Deploy

on:
  workflow_call:
  push:
    branches:
      - develop
    paths:
      - 'packages/api-rails/**'
      - '.github/workflows/api-deploy.yml'

permissions:
  id-token: write
  deployments: write
  statuses: write
  contents: read

defaults:
  run:
    working-directory: ./packages/api-rails
    
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    environment: api-rails/${{github.ref_name == 'main' && 'prod' || github.ref_name == 'develop' && 'stg'}}

    outputs:
      image: ${{ steps.out.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "I am doing a noop deploy"

      - name: Echo vars
        run: echo "HELLO=${{ vars.HELLO }}"

      - name: Set Outputs
        id: out
        run: echo "image=testoutputimagename" >> $GITHUB_OUTPUT

  migrate:
    needs: [build]
    name: DB migrate
    runs-on: ubuntu-latest
    environment: api-rails/${{github.ref_name == 'main' && 'prod' || github.ref_name == 'develop' && 'stg'}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "I am doing a noop deploy"

      - name: Echo output 
        run: echo "image=${{ needs.build.outputs.image }}"

      # - name: Set Outputs
      #   id: out
      #   run: echo "image=${{ needs.build.outputs.image }}" >> $GITHUB_OUTPUT
    
    outputs:
      image: ${{ needs.build.outputs.image }}

  api:
    needs: [migrate]
    name: API Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "I am doing a noop deploy"

      - name: Echo vars
        run: echo "HELLO=${{ vars.HELLO }}"

      - name: Echo output 
        run: echo "image=${{ needs.migrate.outputs.image }}"

  sidekiq:
    needs: [migrate]
    name: Sidekiq Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "I am doing a noop deploy"

  job:
    needs: [migrate]
    name: Job Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "I am doing a noop deploy"
