name: Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      deployment:
        description: デプロイ方法の選択
        required: true
        default: 'Full'
        type: choice
        options:
          - Full
          - Web

permissions:
  id-token: write
  deployments: write
  statuses: write
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo "Deploy started!"

      - name: Echo vars
        run: echo "HELLO=${{ vars.HELLO }}"

  # バックエンドをデプロイする場合
  backend-api:
    needs: [changes]
    if: ${{ inputs.deployment == 'Full' }}
    uses: ./.github/workflows/api-deploy.yml
  frontend-web:
    needs: [backend-api]
    uses: ./.github/workflows/web-deploy.yml 

  # フロントだけデプロイする場合
  frontend-web-only:
    needs: [changes]
    if: ${{ inputs.deployment == 'Web' }}
    uses: ./.github/workflows/web-deploy.yml
